### ISSUE TITLE
Plugging in HDMI Causes Laptop to Crash

### ISSUE THREAD

**Issue by michaeldigiacomi** [michaeldigiacomi/Dell-E7440-Hackintosh#1]
When I plug an HDMI Cable into the HDMI Port of the Laptop Macos Crashes and reboots the laptop. Need to fix this somehow...

**Comment by xiangtailiang** [comment]
Hi,  michael.

I have tested the HDMI Port on my computer  and your issue occur.
I do not use  HDMI Port, so have not been full test.  Sorry for that.

I have fixed this issue, and test OK. You can update from my repo.  Thank you.

Just replace the files in EFI folder.
https://github.com/xiangtailiang/Dell-E7440-Hackintosh

**Comment by michaeldigiacomi** [comment]
Thanks!!!
